### ISSUE TITLE
Training Code for ImageNet

### ISSUE THREAD

**Issue by dronefreak** [d-li14/ghostnet.pytorch#3]
Hi @d-li14 

Could you also share the training code for ghostNet?
I would like to train the model from scratch with some minor improvements of my own for my research.
Thanks in advance!

**Comment by d-li14** [comment]
please refer to https://github.com/d-li14/mobilenetv2.pytorch/blob/master/imagenet.py

**Comment by dronefreak** [comment]
Thanks so much.
