### ISSUE TITLE
A question about size of model(ghostnet_1x-f97d70db.pth) and parameters.

### ISSUE THREAD

**Issue by fourierer** [d-li14/ghostnet.pytorch#4]
Sorry to bother you again, I'm confused about the size of model. The file 'ghostnet_1x-f97d70db.pth' is about 20M, but the parameters is only about 5M as you mentioned. What's the difference between them and how to measure the size of parameters? What's more, how to compute the FLOPs in the model?

**Comment by d-li14** [comment]
Never mind. Is it possible to leave an email here? Maybe a more detailed discussion will be reached.

**Comment by fourierer** [comment]
> Never mind. Is it possible to leave an email here? Maybe a more detailed discussion will be reached.

Thank you so much! I'm a student in CASIA, Beijing. My email address is ''sunzheng2019@ia.ac.cn''.

**Comment by d-li14** [comment]
> > Never mind. Is it possible to leave an email here? Maybe a more detailed discussion will be reached.
> 
> Thank you so much! I'm a student in CASIA, Beijing. My email address is ''[sunzheng2019@ia.ac.cn](mailto:sunzheng2019@ia.ac.cn)''.

Hi, I have sent an email to you regarding your questions.
