### ISSUE TITLE
Custom Weight Initialization Effect

### ISSUE THREAD

**Issue by glenn-jocher** [d-li14/ghostnet.pytorch#7]
I noticed you use code for custom weight initialization:
https://github.com/d-li14/ghostnet.pytorch/blob/83274b7d33580b07d6629415570e894faada7b64/ghostnet.py#L162-L169

I've not seen this before anywhere. Is there a reason behind this specific strategy? Do you know the effect this has on the training, and have you compared this with the pytorch default weight initialization? Thank you!

**Comment by d-li14** [comment]
The same as https://github.com/iamhankai/ghostnet.pytorch/issues/24
